const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');
const Prospect = require('../models/Prospect');

dotenv.config({ path: path.join(__dirname, '../.env') });

const players = [
    {
        name: "Marco Silva",
        email: "marco.silva@example.com",
        phone: "+34600111222",
        dob: new Date("2003-05-12"),
        age: 20,
        position: "Winger",
        nationality: "Spain",
        previousClub: "Betis B",
        leaguesPlayed: ["Segunda División", "RFEF 1"],
        identityCardUrl: "https://example.com/id.jpg",
        isVerified: true,
        isPublicProspect: true,
        scoutReport: "Explosive winger with incredible pace and dribbling ability. Marco excels in 1v1 situations and often penetrates deep into the opposition penalty area. His crossing has improved significantly over the last season. Mentally tough and stays calm under pressure.",
        strengths: ["Pace", "Dribbling", "Acceleration", "Agility"],
        weaknesses: ["Aerial duels", "Defensive tracking"],
        potentialScore: 89,
        pace: 94,
        shooting: 76,
        passing: 81,
        dribbling: 91,
        defending: 45,
        physicality: 68,
        hasInjuryHistory: false,
        fitnessStatus: "Excellent"
    },
    {
        name: "Klaus Schmidt",
        email: "klaus.schmidt@example.com",
        phone: "+491701234567",
        dob: new Date("1998-11-20"),
        age: 25,
        position: "Center Back",
        nationality: "Germany",
        previousClub: "Hamburg SV",
        leaguesPlayed: ["Bundesliga 2"],
        identityCardUrl: "https://example.com/id2.jpg",
        isVerified: true,
        isPublicProspect: true,
        scoutReport: "A towering presence in defense. Klaus is a leader on the pitch with excellent tactical awareness. He is dominant in the air and rarely loses a header. While not the fastest, his positioning allows him to intercept passes effectively. Very disciplined with a high work rate.",
        strengths: ["Heading", "Strength", "Positioning", "Leadership"],
        weaknesses: ["Acceleration", "Turning speed"],
        potentialScore: 82,
        pace: 65,
        shooting: 40,
        passing: 72,
        dribbling: 55,
        defending: 88,
        physicality: 92,
        hasInjuryHistory: true,
        injuryNature: "Minor ankle sprain in 2022",
        fitnessStatus: "Match Fit"
    },
    {
        name: "Luka Modre",
        email: "luka.modre@example.com",
        phone: "+385912345678",
        dob: new Date("2005-02-15"),
        age: 19,
        position: "Midfielder",
        nationality: "Croatia",
        previousClub: "Dinamo Zagreb Academy",
        leaguesPlayed: ["Croatian Youth League"],
        identityCardUrl: "https://example.com/id3.jpg",
        isVerified: false,
        isPublicProspect: true,
        scoutReport: "Technical gifted playmaker with vision far beyond his years. Luka dictates the tempo of the game and has an eye for a killer pass. He is small in stature but very agile and difficult to dispossess. Needs to work on his physical strength for top-tier senior football.",
        strengths: ["Vision", "Passing accuracy", "Ball control", "Stamina"],
        weaknesses: ["Physical strength", "Defending"],
        potentialScore: 92,
        pace: 78,
        shooting: 72,
        passing: 93,
        dribbling: 89,
        defending: 58,
        physicality: 62,
        hasInjuryHistory: false,
        fitnessStatus: "Peak"
    },
    {
        name: "Jean-Pierre Bakayoko",
        email: "jp.bakayoko@example.com",
        phone: "+33612345678",
        age: 22,
        dob: new Date("2002-01-01"),
        position: "Striker",
        nationality: "France",
        previousClub: "Lyon B",
        identityCardUrl: "https://example.com/id4.jpg",
        isPublicProspect: true,
        scoutReport: "Clinical finisher with great movement off the ball. Jean-Pierre is always in the right place at the right time. Strong finisher with both feet, though his left is dominant. He can be quiet for 80 minutes and then score two goals in the final 10. Needs to improve his participation in team build-up.",
        strengths: ["Finishing", "Off-the-ball movement", "Heading", "Composure"],
        weaknesses: ["Work rate", "Passing"],
        potentialScore: 85,
        pace: 84,
        shooting: 90,
        passing: 65,
        dribbling: 78,
        defending: 30,
        physicality: 75,
        isVerified: true
    },
    {
        name: "Ahmed Hassan",
        email: "ahmed.h@example.com",
        phone: "+201012345678",
        age: 24,
        dob: new Date("2000-06-10"),
        position: "Defensive Midfielder",
        nationality: "Egypt",
        previousClub: "Al Ahly",
        identityCardUrl: "https://example.com/id5.jpg",
        isPublicProspect: true,
        scoutReport: "The 'Engine' of the team. Ahmed covers every blade of grass. Exceptional at winning back possession and simple, effective distribution. Very aggressive in the tackle and a set-piece threat due to his height.",
        strengths: ["Aggression", "Interceptions", "Stamina", "Tackling"],
        weaknesses: ["Discipline", "Long-range shooting"],
        potentialScore: 80,
        pace: 74,
        shooting: 55,
        passing: 78,
        dribbling: 70,
        defending: 85,
        physicality: 82,
        isVerified: true
    },
    {
        name: "Carlos Sanchez",
        email: "carlos.s@example.com",
        phone: "+541122334455",
        age: 21,
        dob: new Date("2003-03-15"),
        position: "Left Back",
        nationality: "Argentina",
        previousClub: "River Plate Academy",
        identityCardUrl: "https://example.com/id6.jpg",
        isPublicProspect: true,
        scoutReport: "Modern overlapping full-back with excellent crossing ability. Carlos provides width and constant attacking threat on the left flank.",
        strengths: ["Crossing", "Acceleration", "Overlap"],
        weaknesses: ["Defensive positioning"],
        potentialScore: 87,
        pace: 88,
        shooting: 62,
        passing: 82,
        dribbling: 84,
        defending: 75,
        physicality: 72,
        isVerified: true
    },
    {
        name: "Satoshi Tanaka",
        email: "s.tanaka@example.com",
        phone: "+819011223344",
        age: 23,
        dob: new Date("2001-08-22"),
        position: "Attacking Midfielder",
        nationality: "Japan",
        previousClub: "Yokohama F Marinos",
        identityCardUrl: "https://example.com/id7.jpg",
        isPublicProspect: true,
        scoutReport: "Intelligent playmaker with exceptional close control and vision. Satoshi finds gaps in deep blocks and orchestrates the final third.",
        strengths: ["Vision", "Short Passing", "Agility"],
        weaknesses: ["Strength", "Heading"],
        potentialScore: 84,
        pace: 80,
        shooting: 75,
        passing: 88,
        dribbling: 90,
        defending: 50,
        physicality: 65,
        isVerified: true
    },
    {
        name: "Erik Johansson",
        email: "e.johan@example.com",
        phone: "+46701122334",
        age: 26,
        dob: new Date("1998-02-10"),
        position: "Goalkeeper",
        nationality: "Sweden",
        previousClub: "Malmö FF",
        identityCardUrl: "https://example.com/id8.jpg",
        isPublicProspect: true,
        scoutReport: "Reliable shot-stopper with great command of his area. Erik is excellent in 1v1 situations and has strong distribution skills.",
        strengths: ["Reflexes", "Checking crosses", "Distribution"],
        weaknesses: ["Penalty save rate"],
        potentialScore: 81,
        pace: 55,
        shooting: 25,
        passing: 70,
        dribbling: 45,
        defending: 82,
        physicality: 85,
        isVerified: true
    },
    {
        name: "Victor Osiman",
        email: "v.osiman@example.com",
        phone: "+2348011223344",
        age: 22,
        dob: new Date("2002-12-29"),
        position: "Striker",
        nationality: "Nigeria",
        previousClub: "Lagos Academy",
        identityCardUrl: "https://example.com/id9.jpg",
        isPublicProspect: true,
        scoutReport: "Powerhouse striker with elite vertical jump and finishing. Victor is a constant threat in the air and behind the defense.",
        strengths: ["Jumping Reach", "Finishing", "Strength"],
        weaknesses: ["Dribbling in tight spaces"],
        potentialScore: 91,
        pace: 89,
        shooting: 88,
        passing: 60,
        dribbling: 75,
        defending: 40,
        physicality: 92,
        isVerified: true
    },
    {
        name: "Kevin De Bruyne Jr",
        email: "kdb.jr@example.com",
        phone: "+32470112233",
        age: 18,
        dob: new Date("2006-06-28"),
        position: "Midfielder",
        nationality: "Belgium",
        previousClub: "Genk Youth",
        identityCardUrl: "https://example.com/id10.jpg",
        isPublicProspect: true,
        scoutReport: "The next big thing in Belgian football. Elite passing range and weight of ball. Kevin can find passes no one else sees.",
        strengths: ["Vision", "Long Passing", "Technique"],
        weaknesses: ["Defensive work rate"],
        potentialScore: 95,
        pace: 75,
        shooting: 82,
        passing: 96,
        dribbling: 88,
        defending: 62,
        physicality: 70,
        isVerified: true
    },
    {
        name: "Matheus Pereira",
        email: "m.pereira@example.com",
        phone: "+551199887766",
        age: 24,
        dob: new Date("2000-05-01"),
        position: "Right Winger",
        nationality: "Brazil",
        previousClub: "Santos Academy",
        identityCardUrl: "https://example.com/id11.jpg",
        isPublicProspect: true,
        scoutReport: "Dazzling winger with a trick for every occasion. Matheus loves to cut inside on his left foot and unleash a powerful shot.",
        strengths: ["Flair", "Long Shots", "1v1"],
        weaknesses: ["Consistency"],
        potentialScore: 86,
        pace: 87,
        shooting: 84,
        passing: 78,
        dribbling: 92,
        defending: 35,
        physicality: 68,
        isVerified: true
    },
    {
        name: "Giovanni Rossi",
        email: "g.rossi@example.com",
        phone: "+393331122334",
        age: 25,
        dob: new Date("1999-09-09"),
        position: "Right Back",
        nationality: "Italy",
        previousClub: "Atalanta",
        identityCardUrl: "https://example.com/id12.jpg",
        isPublicProspect: true,
        scoutReport: "Solid defensive full-back who rarely gets beaten. Giovanni is technically sound and disciplined in his role.",
        strengths: ["Tackling", "Marking", "Concentration"],
        weaknesses: ["Attacking output"],
        potentialScore: 83,
        pace: 82,
        shooting: 55,
        passing: 75,
        dribbling: 72,
        defending: 89,
        physicality: 80,
        isVerified: true
    },
    {
        name: "Harry Kane Clone",
        email: "h.kane@example.com",
        phone: "+447788990011",
        age: 27,
        dob: new Date("1997-07-28"),
        position: "Striker",
        nationality: "England",
        previousClub: "Norwich City",
        identityCardUrl: "https://example.com/id13.jpg",
        isPublicProspect: true,
        scoutReport: "Complete forward who can drop deep to playmake or lead the line as a traditional #9. Elite finishing.",
        strengths: ["Finishing", "Passing", "Composure"],
        weaknesses: ["Pace"],
        potentialScore: 88,
        pace: 68,
        shooting: 95,
        passing: 86,
        dribbling: 80,
        defending: 45,
        physicality: 84,
        isVerified: true
    },
    {
        name: "Samuel Eto'o Kid",
        email: "s.etoo@example.com",
        phone: "+237600112233",
        age: 20,
        dob: new Date("2004-03-10"),
        position: "Striker",
        nationality: "Cameroon",
        previousClub: "Kadji Sports Academy",
        identityCardUrl: "https://example.com/id14.jpg",
        isPublicProspect: true,
        scoutReport: "Incredibly fast striker with a nose for goal. Samuel thrives on counter-attacks and finding space behind high lines.",
        strengths: ["Pace", "Acceleration", "Movement"],
        weaknesses: ["Aerial ability"],
        potentialScore: 90,
        pace: 96,
        shooting: 85,
        passing: 68,
        dribbling: 82,
        defending: 35,
        physicality: 74,
        isVerified: true
    },
    {
        name: "Virgil Van Jr",
        email: "vvd.jr@example.com",
        phone: "+31612344321",
        age: 21,
        dob: new Date("2003-01-01"),
        position: "Center Back",
        nationality: "Netherlands",
        previousClub: "Groningen",
        identityCardUrl: "https://example.com/id15.jpg",
        isPublicProspect: true,
        scoutReport: "Composed and physically dominant defender. Virgil Jr reads the game exceptionally well and is a threat at set-pieces.",
        strengths: ["Strength", "Interceptions", "Aerial"],
        weaknesses: ["Agility"],
        potentialScore: 92,
        pace: 84,
        shooting: 60,
        passing: 80,
        dribbling: 70,
        defending: 91,
        physicality: 94,
        isVerified: true
    },
    {
        name: "Leroy Sane II",
        email: "ls.ii@example.com",
        phone: "+491601122334",
        age: 22,
        dob: new Date("2002-01-11"),
        position: "Winger",
        nationality: "Germany",
        previousClub: "Schalke 04 Academy",
        identityCardUrl: "https://example.com/id16.jpg",
        isPublicProspect: true,
        scoutReport: "Lightning-fast winger with smooth dribbling and great explosive power. He can beat any defender in a sprint.",
        strengths: ["Speed", "Dribbling", "Acceleration"],
        weaknesses: ["Work rate"],
        potentialScore: 88,
        pace: 95,
        shooting: 81,
        passing: 78,
        dribbling: 90,
        defending: 42,
        physicality: 70,
        isVerified: true
    },
    {
        name: "N'Golo Kante Clone",
        email: "nk.clone@example.com",
        phone: "+33600112233",
        age: 23,
        dob: new Date("2001-03-29"),
        position: "Defensive Midfielder",
        nationality: "France",
        previousClub: "Caen",
        identityCardUrl: "https://example.com/id17.jpg",
        isPublicProspect: true,
        scoutReport: "The player who is everywhere. Relentless pressing and world-class ball recovery. A nightmare for opposing playmakers.",
        strengths: ["Stamina", "Tackling", "Work Rate"],
        weaknesses: ["Shooting"],
        potentialScore: 89,
        pace: 82,
        shooting: 58,
        passing: 80,
        dribbling: 78,
        defending: 94,
        physicality: 82,
        isVerified: true
    },
    {
        name: "Pedri de la Fuente",
        email: "pdf@example.com",
        phone: "+34611223344",
        age: 19,
        dob: new Date("2005-11-25"),
        position: "Midfielder",
        nationality: "Spain",
        previousClub: "Las Palmas",
        identityCardUrl: "https://example.com/id18.jpg",
        isPublicProspect: true,
        scoutReport: "Graceful midfielder with sublime touch and positional awareness. He plays football like he's in a park. Total control.",
        strengths: ["Control", "Vision", "Short Pass"],
        weaknesses: ["Shooting power"],
        potentialScore: 94,
        pace: 76,
        shooting: 72,
        passing: 94,
        dribbling: 91,
        defending: 68,
        physicality: 65,
        isVerified: true
    },
    {
        name: "Alphonso Roadrunner",
        email: "arr@example.com",
        phone: "+14161234567",
        age: 21,
        dob: new Date("2003-11-02"),
        position: "Left Back",
        nationality: "Canada",
        previousClub: "Vancouver Whitecaps",
        identityCardUrl: "https://example.com/id19.jpg",
        isPublicProspect: true,
        scoutReport: "Converted winger who uses his world-class speed to recover defensive positions and join attacks. Fastest LB in the pool.",
        strengths: ["Speed", "Recovery", "Dribbling"],
        weaknesses: ["Aerial Duels"],
        potentialScore: 92,
        pace: 97,
        shooting: 70,
        passing: 78,
        dribbling: 89,
        defending: 78,
        physicality: 80,
        isVerified: true
    },
    {
        name: "Jan Oblak Jr",
        email: "joj@example.com",
        phone: "+38640112233",
        age: 24,
        dob: new Date("2000-01-07"),
        position: "Goalkeeper",
        nationality: "Slovenia",
        previousClub: "Olimpija Ljubljana",
        identityCardUrl: "https://example.com/id20.jpg",
        isPublicProspect: true,
        scoutReport: "Immoveable wall in goal. Exceptional handling and composure. He rarely makes mistakes and is a rock for his defense.",
        strengths: ["Handling", "Positioning", "Composure"],
        weaknesses: ["Brave on the ball"],
        potentialScore: 90,
        pace: 52,
        shooting: 22,
        passing: 68,
        dribbling: 48,
        defending: 88,
        physicality: 82,
        isVerified: true
    }
];

const seedDB = async () => {
    try {
        await mongoose.connect(process.env.MONGODB_URI);
        console.log("Connected to MongoDB");

        // Clear existing players or keep them? 
        // Let's just add new ones to avoid deleting user's real data
        // await Player.deleteMany({ email: { $in: players.map(p => p.email) } });

        for (const player of players) {
            await Prospect.findOneAndUpdate(
                { email: player.email },
                player,
                { upsert: true, new: true }
            );
        }

        console.log("Mock players seeded successfully!");
        mongoose.connection.close();
    } catch (error) {
        console.error("Error seeding database:", error);
        process.exit(1);
    }
};

seedDB();
